trigger:
  branches:
    include:
     - main

pr:
  drafts: false
  branches:
    include:
     - main

parameters:
- name: browser
  displayName: Browser Authorization
  type: boolean
  default: true

- name: electron
  displayName: Electron Authorization
  type: boolean
  default: true

- name: service
  displayName: Service Authorization
  type: boolean
  default: true

- name: nodeCli
  displayName: Node CLI
  type: boolean
  default: true

- name: shouldPublish
  displayName: Publish?
  type: boolean
  default: false

resources:
  repositories:
    - repository: itwinjs-core
      type: github
      endpoint: iModelJs
      name: iTwin/itwinjs-core
      ref: refs/heads/master

stages:
  - stage: Generate_Docs
    jobs:
    - job:
      displayName: iTwin Auth Clients Generate Docs
      workspace:
        clean: all

      steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          displayName: Use Node 18
          inputs:
            versionSpec: 18
            checkLatest: true

        - script: |
            git config --local user.email imodeljs-admin@users.noreply.github.com
            git config --local user.name imodeljs-admin
          displayName: Setup git config

        - script: node common/scripts/install-run-rush.js install
          displayName: Rush Install

        - template: templates/build-docs.yaml
          parameters:
            browser: ${{parameters.browser}}
            service: ${{parameters.service}}
            electron: ${{parameters.electron}}
            "node-cli": ${{parameters.nodeCli}}
            shouldPublish: ${{parameters.shouldPublish}}

