trigger:
  branches:
    include:
     - main

pr:
  drafts: false
  branches:
    include:
     - main

pool:
  vmImage: "windows-latest" # used because we publish from windows agents

parameters:
- name: browser
  displayName: Browser Authorization
  type: boolean
  default: true

- name: electron
  displayName: Electron Authorization
  type: boolean
  default: true

- name: service
  displayName: Service Authorization
  type: boolean
  default: true

- name: nodeCli
  displayName: Node CLI
  type: boolean
  default: true

- name: shouldPublish
  displayName: Publish?
  type: boolean
  default: false

resources:
  repositories:
    - repository: itwinjs-core
      type: github
      endpoint: iModelJs
      name: iTwin/itwinjs-core
      ref: refs/heads/master

stages:
  - stage: Generate_Docs
    jobs:
    - job:
      displayName: iTwin Auth Clients Generate Docs
      workspace:
        clean: all

      steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          displayName: Use Node 18
          inputs:
            versionSpec: 18
            checkLatest: true

        - script: npm install -g pnpm@7.27.0
          displayName: Install pnpm

        - script: |
            git config --local user.email imodeljs-admin@users.noreply.github.com
            git config --local user.name imodeljs-admin
          displayName: Setup git config

        - bash: |
            echo "electron is ${{parameters.electron}}"
            echo "browser is ${{parameters.browser}}"
            echo "service is ${{parameters.service}}"
            echo "nodeCli is ${{parameters.nodeCli}}"
            if [[ ${{ parameters.browser }} = 'True' ]]; then
              echo "setting browser to true"
              echo "##vso[task.setvariable variable=browser;isOutput=true;]true"
            fi

            if [[ ${{ parameters.electron }} = 'True' ]]; then
              echo "setting electron to true"
              echo "##vso[task.setvariable variable=electron;isOutput=true;]true"
            fi

            if [[ ${{ parameters.service }} = 'True' ]]; then
              echo "setting service to true"
              echo "##vso[task.setvariable variable=service;isOutput=true;]true"
            fi

            if [[ ${{ parameters.nodeCli }} = 'True' ]]; then
              echo "setting node-cli to true"
              echo "##vso[task.setvariable variable=node-cli;isOutput=true;]true"
            fi
          displayName: set variables
          name: releaseNotes

        - script: pnpm install
          displayName: Install packages

        - template: templates/build-docs.yaml
          parameters:
            shouldPublish: ${{parameters.shouldPublish}}

  - stage: Validate_Docs
    dependsOn: Generate_Docs
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'PullRequest', 'Manual'))
    jobs:
    - template: common/config/azure-pipelines/jobs/docs-build.yaml@itwinjs-core
      parameters:
        checkout: itwinjs-core
        useCurrentAuthClientsDocsArtifact: true
        ignoreAudit: true
