parameters:
  - name: shouldPublish
    displayName: Publish?
    type: boolean
    default: false

steps:
  # Because we may not publish all of our packages at once,
  # we must add these new docs to the existing artifact.
  - task: DownloadPipelineArtifact@2
    displayName: Download existing docs
    inputs:
      buildType: "specific"
      project: "2c48216e-e72f-48b4-a4eb-40ff1c04e8e4"
      definition: "9074"
      buildVersionToDownload: "latest"
      tags: "hasDocs"
      allowPartiallySucceededBuilds: true
      allowFailedBuilds: true
      artifactName: "iTwin-Auth-Clients Docs"
      targetPath: "$(Build.StagingDirectory)/docs"
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - script: |
      pnpm run docs --scope @itwin/electron-authorization
    env:
      RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)
    displayName: "Build electron-authorization docs"
    condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['releaseNotes.electron'], 'true'))

  - script: |
      pnpm run docs --scope @itwin/service-authorization
    env:
      RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)
    displayName: "Build service-authorization docs"
    condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['releaseNotes.service'], 'true'))

  - script: |
      pnpm run docs --scope @itwin/node-cli-authorization
    env:
      RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)
    displayName: "Build node-cli-authorization docs"
    condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['releaseNotes.node-cli'], 'true'))

  - script: |
      pnpm run docs --scope @itwin/browser-authorization
    env:
      RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)
    displayName: "Build browser-authorization docs"
    condition: and(eq(variables['Agent.OS'], 'Windows_NT'), eq(variables['releaseNotes.browser'], 'true'))

  - task: CopyFiles@2
    displayName: "Copy generated docs to: $(Build.StagingDirectory)"
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/generated-docs/auth-clients
      TargetFolder: $(Build.StagingDirectory)/docs
      OverWrite: true
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: Auth-Clients Docs"
    inputs:
      PathtoPublish: "$(Build.StagingDirectory)/docs/"
      ArtifactName: "iTwin-Auth-Clients Docs"
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

  - task: tagBuildOrRelease@0
    inputs:
      type: "Build"
      tags: "hasDocs"
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), ${{ parameters.shouldPublish }} )
