parameters:
  - name: shouldPublish
    displayName: publish?
    type: boolean
    default: false

steps:
  # Because we may not publish all of our packages at once,
  # we must add these new docs to the existing artifact.
  - task: DownloadPipelineArtifact@2
    displayName: Download existing docs
    inputs:
      buildType: "specific"
      project: "2c48216e-e72f-48b4-a4eb-40ff1c04e8e4"
      definition: "9074"
      buildVersionToDownload: "latest"
      tags: "hasDocs"
      allowPartiallySucceededBuilds: true
      allowFailedBuilds: true
      artifactName: "iTwin-Auth-Clients Docs"
      targetPath: "$(Build.StagingDirectory)/docs"
    condition: and(succeeded(), ${{ parameters.shouldPublish }})

  - ${{ if eq(variables.electron, 'true') }}:
      - script: |
          node common/scripts/install-run-rush.js docs --only electron-authorization
          mv $(Build.SourcesDirectory)/generated-docs/auth-clients/electron "$(Build.SourcesDirectory)/generated-docs/auth-clients/electron-authorization"
        env:
          RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)
        displayName: "Build electron-authorization docs"

  - ${{ if eq(variables.service, 'true') }}:
      - script: |
          node common/scripts/install-run-rush.js docs --only service-authorization
          mv $(Build.SourcesDirectory)/generated-docs/auth-clients/service "$(Build.SourcesDirectory)/generated-docs/auth-clients/service-authorization"
        env:
          RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)
        displayName: "Build service-authorization docs"

  - ${{ if eq(variables['node-cli'], 'true') }}:
      - script: |
          node common/scripts/install-run-rush.js docs --only electron-authorization
          mv $(Build.SourcesDirectory)/generated-docs/auth-clients/node-cli "$(Build.SourcesDirectory)/generated-docs/auth-clients/node-cli-authorization"
        env:
          RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)
        displayName: "Build node-cli-authorization docs"

  - ${{ if eq(variables.browser, 'true') }}:
      - script: |
          node common/scripts/install-run-rush.js docs --only browser-authorization
          mv $(Build.SourcesDirectory)/generated-docs/auth-clients/browser "$(Build.SourcesDirectory)/generated-docs/auth-clients/browser-authorization"
        env:
          RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)
        displayName: "Build browser-authorization docs"

  - task: CopyFiles@2
    displayName: "Copy generated docs to: $(Build.StagingDirectory)"
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/generated-docs/auth-clients
      TargetFolder: $(Build.StagingDirectory)/docs
      OverWrite: true
    condition: and(succeeded(), ${{ parameters.shouldPublish }})

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: Auth-Clients Docs"
    inputs:
      PathtoPublish: "$(Build.StagingDirectory)/docs/"
      ArtifactName: "iTwin-Auth-Clients Docs"
    condition: and(succeeded(), ${{ parameters.shouldPublish }} )

  - task: tagBuildOrRelease@0
    inputs:
      type: "Build"
      tags: "hasDocs"
    condition: and(succeeded(), ${{ parameters.shouldPublish }} )
