parameters:
  - name: electron # name of the parameter; required
    type: boolean # data type of the parameter; required
    default: false
  - name: service # name of the parameter; required
    type: boolean # data type of the parameter; required
    default: false
  - name: browser # name of the parameter; required
    type: boolean # data type of the parameter; required
    default: false

steps:
  - ${{ each parameter in parameters }}:
      - bash: echo "${{parameter.Key}} is ${{parameter.Value}}"
      - ${{ if eq(variables[parameter.Key], 'true')}}:
          - bash: |
              echo "${{parameter.Key}} is: ${{parameter.Value}}"
              echo "variables attempt ${{variables[parameter.Key]}}"
            displayName: Test Variable Sets

  - bash: |
      echo "${{variables["electron"]}}"
      echo "${{parameters[variables]}}"
    displayName: reconcile parameters and variables
