parameters:
  - name: electron # name of the parameter; required
    type: boolean # data type of the parameter; required
    default: false
  - name: service # name of the parameter; required
    type: boolean # data type of the parameter; required
    default: false
  - name: browser # name of the parameter; required
    type: boolean # data type of the parameter; required
    default: false

steps:
  - ${{ each parameter in parameters }}:
      - bash: |
          echo "##vso[task.setvariable variable=electronCombined;isoutput=true]setVars.${{parameter.Key}}"
          echo $(electronCombined)
          echo ${{variables[$(electronCombined)]}}
          echo "${{parameter.Key}} is ${{parameter.Value}}"
      - ${{ if eq(variables[parameter.Key], 'true')}}:
          - bash: |
              echo "${{parameter.Key}} is: ${{parameter.Value}}"
              echo "variables attempt $(setVars[parameter.Key])"
            displayName: Test Variable Sets

  - bash: |
      echo "$(setVars['electron'])"
    displayName: reconcile parameters and variables
