parameters:
  - name: paramOne # name of the parameter; required
    type: string # data type of the parameter; required

steps:
  - bash: |
      echo "varone is $(varOne)"
      echo "paramOne is ${{parameters.paramOne}}"
    displayName: Add Release Notes
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), ${{ parameters.shouldPublish }} )
