trigger:
  branches:
    include:
     - main

pr:
  drafts: false
  branches:
    include:
     - main

parameters:
- name: browser
  displayName: Browser Authorization
  type: boolean
  default: true

- name: desktop
  displayName: Desktop Authorization
  type: boolean
  default: true

- name: service
  displayName: Service Authorization
  type: boolean
  default: true

- name: node-cli
  displayName: Node CLI
  type: boolean
  default: true

resources:
  repositories:
    - repository: itwinjs-core
      type: github
      endpoint: iModelJs
      name: iTwin/itwinjs-core
      ref: refs/heads/master

stages:
  - stage: Generate_Docs
    jobs:
    - job:
      displayName: iTwin Auth Clients Generate Docs
      workspace:
        clean: all

      steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          displayName: Use Node 18
          inputs:
            versionSpec: 18
            checkLatest: true

        - script: |
            git config --local user.email imodeljs-admin@users.noreply.github.com
            git config --local user.name imodeljs-admin
          displayName: Setup git config

        - script: node common/scripts/install-run-rush.js install
          displayName: Rush Install

        - script: node common/scripts/install-run-rush.js docs
          displayName: Rush Generate Docs
          env:
            RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)

        - ${{ each parameter in parameters }} :
          - script: |
              if [[ ${{ parameter.Value }} ]]; then
                echo ${{parameter.Key}} ${{parameter.Value}}
                node common/scripts/install-run-rush.js docs --only "${{$parameter.Key}}-authorization"
                mv $(Build.SourcesDirectory)/generated-docs/auth-clients/${{$parameter.Key}} "$(Build.SourcesDirectory)/generated-docs/auth-clients/${{$parameter.Key}}-authorization"
              fi
            env:
              RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)

        - task: CopyFiles@2
          displayName: 'Copy generated docs to: $(Build.StagingDirectory)'
          inputs:
            SourceFolder: $(Build.SourcesDirectory)/generated-docs/auth-clients
            TargetFolder: $(Build.StagingDirectory)/docs

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: Auth-Clients Docs'
          inputs:
            PathtoPublish: '$(Build.StagingDirectory)/docs/'
            ArtifactName: 'iTwin-Auth-Clients Docs'

  - stage: Validate_Docs
    dependsOn: Generate_Docs
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'PullRequest', 'Manual'))
    jobs:
    - template: common/config/azure-pipelines/jobs/docs-build.yaml@itwinjs-core
      parameters:
        checkout: itwinjs-core
        useCurrentPresentationDocsArtifact: true