trigger:
  branches:
    include:
     - main

pr:
  drafts: false
  branches:
    include:
     - main

resources:
  repositories:
    - repository: itwinjs-core
      type: github
      endpoint: iModelJs
      name: iTwin/itwinjs-core
      ref: refs/heads/master

stages:
  - stage: Generate_Docs
    jobs:
    - job:
      displayName: iTwin Auth Clients Generate Docs
      workspace:
        clean: all

      steps:
        - checkout: self
          clean: true

        - task: NodeTool@0
          displayName: Use Node 18
          inputs:
            versionSpec: 18
            checkLatest: true

        - name: Rush Install
          run: node common/scripts/install-run-rush.js install

        - name: Rush Generate Docs
          run: node common/scripts/install-run-rush.js docs
          env:
            RUSHSTACK_FILE_ERROR_BASE_FOLDER: $(Build.SourcesDirectory)

        - task: CopyFiles@2
          displayName: 'Copy generated docs to: $(Build.StagingDirectory)'
          inputs:
            SourceFolder: $(Build.SourcesDirectory)/build
            TargetFolder: $(Build.StagingDirectory)

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: Auth-Clients Docs'
          inputs:
            PathtoPublish: '$(Build.StagingDirectory)/docs/'
            ArtifactName: 'iTwin-Auth-Clients Docs'

  - stage: Validate_Docs
    dependsOn: Generate_Docs
    condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'PullRequest', 'Manual'))
    jobs:
    - template: common/config/azure-pipelines/jobs/docs-build.yaml@itwinjs-core
      parameters:
        checkout: itwinjs-core
        useCurrentPresentationDocsArtifact: true