name: Create GitHub Release

on:
  push:
    tags:
      - "**"
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # checkouts the branch that triggered the workflow
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin

      - name: Create GitHub release
        run: |
          echo "Creating GitHub release for tag ${{ github.ref }}"
          gh release create @itwin/service-authorization_v1.2.3 /packages/service --verify-tag
          # scripts/create-release.sh ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.IMJS_ADMIN_GH_TOKEN }}