name: Create GitHub Release

on:
  push:
    tags:
      - '@itwin/*_v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # checkouts the branch that triggered the workflow
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Configure git
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin

      - name: Create GitHub release
        run: |
          echo "Creating GitHub release for tag ${{ github.ref }}"
          bash .github/workflows/scripts/create-release.sh ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.IMJS_ADMIN_GH_TOKEN }}