# Workflow that will create a GitHub release a when a new release tag is pushed

name: Create Release

on:
  push:
    tags:
      - "**"
jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin

      - name: Create release
        run: pnpm run publish-packages --publish --push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
