name: Publish Packages to npm

on: workflow_dispatch

jobs:
  release-packages:
    runs-on: ubuntu-latest

    name: Release packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.IMJS_ADMIN_GH_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build, Lint, Test
        run: pnpm lage build lint cover

      - name: Publish packages and create git tags
        run: |
          git config --local user.email imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin
          pnpm publish-packages -y --branch ${{ github.ref_name }} --message "Version bump [skip actions][publish docs]"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}
